### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by kevin-shu** [vast-engineering/express-vhost#1]
Hi, when I follow your tutorial building the vhost, I encounter a error at index.js:4:

<!DOCTYPE html>
^
SyntaxError: Unexpected token <

How should I solve this problem?Thanks~

**Comment by panthershark** [comment]
I see you closed this.  Were you able to get it working?

**Comment by kevin-shu** [comment]
Well.... it's a stupid mistake....please forget about it....
Thanks for your help~ Your product is awesome~ :)

2012/10/26 Tommy Messbauer notifications@github.com

> I see you closed this. Were you able to get it working?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/vast-eng/express-vhost/issues/1#issuecomment-9800473.

## 

_Best Regards, *
*Kevin Shu_
