### ISSUE TITLE
Does express-vhost help to implement subdomain routing?

### ISSUE THREAD

**Issue by wle8300** [vast-engineering/express-vhost#3]
I've seen some solutions online for setting up subdomains, and most require creating a separate folder for the other servers. For example, so that, `m.soundcloud.com` actually launches a different app than `soundcloud.com`.

Does this plugin get around this?

**Comment by panthershark** [comment]
Yes it solves the problem of running multiple sites under one server on one port. 

E.g.
http://foo.com:8081
http://baz.com:8081
http://bar.baz.com:8081

All of these can run as a single server, delegating to he correct app. 

It does not force you to put the apps in folders or anything, just that you register them on specific domains. Where someone puts their code is up to them.

**Comment by wle8300** [comment]
That's cool. I'm trying to get this to work, and not sure if I'm doing something wrong.

```
var evh = require('express-vhost')
var server = express();
server.use(evh.vhost());

var appFactory = function(jadeName) {
    var app = express();
    app.get('/', function(req, res) {
        res.render(jadeName, {title: JadeName});
    });
    return app;
};

evh.register('contact.localhost:3333', appFactory('contact'));

server.listen(server.get('port'), function() {
  console.log('Express server listening on port ' + server.get('port'));
});
```

I'm developing locally, and trying to get `contact.localhost:3333` to render the `contact.jade` template. (I added `127.0.0.1   contact.localhost` to /etc/hosts).

**Comment by panthershark** [comment]
Remove the port number from the register function.  Then it should work.  The port is set at the main express server.

``` javascript
evh.register('contact.localhost', appFactory('contact'));
```

**Comment by wle8300** [comment]
Hm. That seems to break it.

I'm using Chrome and I just get the message `Oops! Google Chrome could not find contact.localhost:3333`. Do you have any idea why? I'm on a mac, using Express 3.

**Comment by wle8300** [comment]
Nvmind. I figured it out. It was a dumb typo unrelated to this module.

Thanks for the help @tommydudebreaux, and for making this awesome plugin. Not sure why this repo doesn't get more love. The other plugins suck.

**Comment by panthershark** [comment]
Thanks!  

:)
