### ISSUE TITLE
Not using subdomain breaks vhost

### ISSUE THREAD

**Issue by unphased** [vast-engineering/express-vhost#5]
This is the place in the code that causes breakage: 

```
if (!server){
     server = hostDictionary['*' + host.substr(host.indexOf('.'))];
}
```

No doubt implemented this way to avoid huge nasty regexes but this will not work because it will cull the entire domain if the hostname doesn't have a sub-domain like `www`.

To be specific: Given a hostname such as `site.com` this will attempt to fetch from the dict a value `*.com`, which will fail.

Chief among various solutions/workarounds is having an appropriate DNS CNAME entry to forward the naked comain to `www` subdomain. But this is definitely a bug in my eyes to not deal with this particular situation. As for the various complexities involved with getting a website working properly with a naked domain, that's out of the scope of this discussion, I reckon.

FWIW, I experienced the same sort of issue with the other `vhost` middleware, so their fancy regexes apparently aren't solving this issue either, though I haven't actually looked into what the deal is there. But just looking at the source, I'd much rather use `express-vhost` anyway.

**Comment by panthershark** [comment]
Hi @unphased . Thanks so much for the bug report.  I no longer work for Vast and it does not seem that anyone is maintaining these open source libraries there any longer.  

I created a fork over here  - https://github.com/tommymessbauer/express-vhost

If you submit and example or a PR there, then I'll be happy to merge it and publish to npm.

**Comment by unphased** [comment]
Cool, well I don't have this forked and fixed yet, since one of the many easy ways around the issue was basically to not send anybody any links that use the naked domain with my webpage. When I do make my way back to fixing up my websites more, I think I will fix this (match a `*`-url to a single subdomain domain request url OR url with no subdomain?). 

It could actually be argued that `*.site.com` shouldn't even match `site.com`. I can't even decide which side of that fence I'm on! 

But such a quirk should be mentioned in documentation at the very least. 

In this context, the behavior of `site.com` trying to match `*.com` is actually more or less justified from a logical perspective, it just happens not to align well with developer intentions.

So if I actually follow through with my reasoning this time around, I can simply apply two mappings, `*.site.com`, `site.com`, (and various `*.*.site.com`, conceptually, though i think the code doesn't do a regex check for this so it will not get matched up -- we'd need to specify e.g. `*.subdomain.site.com`) and no code change is necessary. And it's more technically correct for the usual meanings of `*`.
